title: Zihan Yang's Homepage
page-top-title: ZiHan Yang
top-section-bg-text: Computer Science
home-subtitle: Zihan Yang&ensp;|&ensp;杨子涵
copyright-text: '&copy; Zihan Yang 2024-2025. All Rights Reserved.'
